### PR TITLE
feat!: Adapt Restify to JSONAPI standards

### LINKED ISSUE #562: Store/Update requests aren't working with JSONAPI payload format
Hi,

if I try to send to the POST endpoint (store) the following payload (compliant with [JSONAPI specs](https://jsonapi.org/format/#crud-creating)):

```json
{
  "type": "users",
  "attributes": {
    "username": "test",
    "email": "test@test.tl"
  },
  "relationships": {}
}
```

I get the following error:

```json
{
  "message": "username is required. (and 1 more error)",
  "errors": {
    "username": [
      "username is required."
    ],
    "email": [
      "email is required."
    ]
  }
}
```

I've found out Restify only accepts a plain payload of type `[attribute => value]`, like this:

```json
{
    "username": "test",
    "email": "test@test.tl"
}
```

By the way, this works but due to this Restify isn't fully compliant with JSONAPI (the docs home page says "JSON:API consistency" under features).

Can you support the JSONAPI payload schema?

Thanks

### PR DESCRIPTION
**Pull request by maicol07**
Fixes #558 
Will fix: #562

Progress:
- Show/Index
	- [x] [Relationships](https://jsonapi.org/format/#document-resource-object-relationships) (missing links)
	- [x] [Included](https://jsonapi.org/format/#document-top-level)
	- [ ] ~[Sparse fieldsets](https://jsonapi.org/format/#fetching-sparse-fieldsets) (low priority) #523~ (will be handled in #536) 
  - [ ] ~[JSONAPI object](https://jsonapi.org/format/#document-jsonapi-object) (low priority)~
- [x] [Relationships endpoints](https://jsonapi.org/format/#fetching-relationships) (low priority)
	- [ ] ~Policies?~ (Policies are already used in related endpoints)
- [x] Filtering/Matching (with [filter](https://jsonapi.org/format/#fetching-filtering) query parameter)
- [x] [Relationships update when updating attributes](https://jsonapi.org/format/#crud-updating-resource-relationships)
- [x] Tests
- [ ] ⚒️ Documentation

> ⚒️ means "Currently in progress"

### CODE REVIEW

**Comment by binaryk** [comment]
I think you can use the `$eagerState` property instead of isRelationship.

**Comment by maicol07** [comment]
> I think you can use the `$eagerState` property instead of isRelationship.

The issue here is that `$eagerState` is used for the included (old relationships array). I need something else to identify the new slim relationships array and the included one. Maybe I can use an enum since Restify targets PHP 8.1+?

**Comment by maicol07** [comment]
@binaryk I think the PR is ready to be reviewed. The only thing left is a documentation update to cover the new API format (I guess this can be labeled as Restify 9.0?)

There is also a test failing but I don't know how to fix it (I think I need your help for this one :sweat\_smile:)! Basically, it seems nested relationships aren't added to included. Related code:

[https://github.com/maicol07/laravel-restify/blob/b0da4d86ab16b4ae9d05e118200d799e7213437b/src/Repositories/Repository.php#L542-L553](https://github.com/maicol07/laravel-restify/blob/b0da4d86ab16b4ae9d05e118200d799e7213437b/src/Repositories/Repository.php#L542-L553)

**Comment by binaryk** [comment]
Thanks @maicol07 , can we make sure tests pass please?

**Comment by maicol07** [comment]
> Thanks @maicol07 , can we make sure tests pass please?

Yes, I want the last test to pass, however I tried to debug it but I can't understand why nested relationships aren't loaded in included. Am I missing something?

**Comment by binaryk** [comment]
@maicol07 I'll have to close this due to inactivity. Now we're on branch 9.x. Please let us know if you want to support it further.

**Pull request closed without merging**
