### PR TITLE
fix: required is not added to rules and rules overriding

### PR DESCRIPTION
**Pull request by maicol07**

### CODE REVIEW

**Comment by binaryk** [comment]
Please fix tests and add a unit test that covers this functionality. 

Thank you!

**Comment by maicol07** [comment]
@binaryk done! However, I don't know where to add a test for this methods (related to rules)

**Comment by binaryk** [comment]
Thank you for your contribution, however at this point we cannot merge PR's without tests. 

More than that, the fluent API should follow the Laravel Nova way, using that method to overwrite rules doesn't feels natural.

**Comment by maicol07** [comment]
@binaryk I'll redo the PR with just the fix for the issue without overriding anything

**Comment by maicol07** [comment]
The new PR is this one: #575

**Pull request closed without merging**
